sudo: required
dist: xenial
services:
- docker
script: make
notifications:
  email: false
  slack:
    rooms:
      secure: ZlkvDth4/2lk8PqAnIRNLs33phCwB+zFAxu8TCEcqzlEOLT7VRXvPXM7AOgqXyLHSudBqF2/adYZZ24AJ33HenGf9xmJX/8Tku0c4D/mR0qT6L4W8uNCvTjcIQyDP1g0wbUIVeS2Din6JVe1M4BbkyzJ03xbhwKkM7jtFQ0mj0gtBufSRdNfXiV2Ivr9H0ys71MrUh4U8USOLbsDZEwDHjQJLB1dZ5P8rG29lA/k+8ktjyf+E6JbtSH58SlDhqyEqf6LYM/07/mWCZaXt6NqUH3z0d7G3GuEnjQbYSSihDPRmXQaWzdsj+OKcW93zRBfH+uSdz6OnY01jrECkYz3XTtHRZ8ImUInUh1wjPqQa5Iqu2I4bLorx/4RtOxdcU7wAhl6paDV8Xclr8fl5kATuD+Joc1yCLufX/T02do9XBBJn93aBe0YNMNfEgL6xrB62JQzy9BPJSIidBC1gVRDFfuKUbDC270Tc19vVqylL4LaaD3yiLGuspnsW3tvA0RC0u3SLXFyg0G1GnoR8GcihcJRidZ7XlLzTiz4VbUPEzebBm0fuASM01+eq7DNEZ/Ii5VnLHBinzbMn1nsXy9iYfxc0xjMuS39GMKC4qeAPR3sso9zATNgF9oCNYP+vVlhrBLiZolMHUn+6BoQYmUhUbE6Fjp5v5nqqrkG2HuEDzM=
env:
  global:
    secure: bjwKfgrCX+dFlpkLxreGHWsFLcfKc1MsKvi/5ODgvYQPFWKt9x7YEj3nWiF/nVYn078IMOTk4NbrVwgxa0lpz4uGEJ8zW8iBZm+/WvW83ppsOaHXmpF5HqlZYlpUAGGGNtjJkG9ZFEAdOgDwJ369CAVmYdfyC2rqh5DJxwFnw91F29JTL/f6zMbiABHPw7dJyHEkKB6ZXT+UkaK0r+ZdGTSMLh66BAchutPFDJGmnqG7MZYBfuX+D7mNGy+F9q+N9Hpg42PEKY/uznW4CfzZ2tKNMJMKM1um3anKTP/YM8prQAkoy99UUfxrKkKPAZzVo2gWsohdetzoCVh1V2TeFss3kSzIF1x3xMSFtuTHWafofeUeQQ9NA0Iw56lISeXUEWNexmXmBqOiF9ErZ4b6HoUYP11Wgkwnzp9ctsMM8gS0PS2nWgvHVLM5s9YQczB6NjHI/b3mMrDZ3BLTTfrkWqJioTg+GjViGayqqFXjZZhwn3nuaBIqOh1UWemgywCoKOfN4POpZinVN6XK2b3AxGrXQfocF8phgwkfZ1TlSMXZwo8EqHL/n+sXSLJGSZBc5f7FpfcSQ6zT7Lpbt8pe/HyCOroESqUuN4goLkUmDKcN7FOQCIF0ERU29WjxOM/nbZOZ/EIONAdaRJlIrRSC3vQHO4woE7aSNSOFousnC0I=
